### ISSUE TITLE
Support persistent on toast notifications

### ISSUE THREAD

**Issue by pmuir** [fabric8-ui/ngx-widgets#24]
According to http://www.patternfly.org/pattern-library/communication/toast-notifications/#/api if the persistent flag is not set the notification should disappear after a time period (default 8s). This is not implemented (need to disappear and to be able to set the timeout).

**Comment by dlabrecq** [comment]
The notification components are intended to work with a service which controls the timeouts to make them disappear or persist. I have not converted the Angular Patternfly notification service yet.

**Comment by dlabrecq** [comment]
Please see PR #35. The newly added notification service supports this feature.

**Comment by pmuir** [comment]
LGTM
