### ISSUE TITLE
Implement Compound Expansion List View 

### ISSUE THREAD

**Issue by pmuir** [fabric8-ui/ngx-widgets#50]
For reference http://www.patternfly.org/pattern-library/content-views/list-view/

**Comment by dlabrecq** [comment]
I've implemented compound expansion for the patternfly-ng repo.

I've also moved several components from ngx-widgets there as well. Not sure if we will port compound expansion to ngx-widgets? The idea was to begin using patternfly-ng instead -- it should be ready shortly.

**Comment by dlabrecq** [comment]
This is available in patternfly-ng
