### ISSUE TITLE
Type ahead search support for filter drop down

### ISSUE THREAD

**Issue by sanbornsen** [fabric8-ui/ngx-widgets#71]
UX - https://redhat.invisionapp.com/share/56AH8F1XM#/screens/219275641

## Requirement:

* The filter drop down should have an input box.
* After selecting a filter field, clicking on the input field or the caret should emit an event back with the filter type.
* Based on that event, options will be added to the query list for that filter field.
* A loader should be shown until we have the data pushed to query list.
* With the empty input box all the results in query list will be shown.
* On type ahead results should be filtered and highlighted based on the search string. (We already have a pipe for the highlight feature, called ```alm-search-highlight.pipe```)
* Query list can have image url or icon class with each of the item, that should be handled and shown in the dropdown.

## Special case:

* On typeahead event should also be thrown back to planner so that, in future if we want to integrate search API on typeahead for a field we can do that.

**Comment by dlabrecq** [comment]
This is available and also added to patternfly-ng.
