### ISSUE TITLE
Remove filters-field font size

### ISSUE THREAD

**Issue by SMahil** [fabric8-ui/ngx-widgets#73]
Filter fields css are overwriting the base font size.

**Comment by dlabrecq** [comment]
Platform and Planner are now using the filter from patternfly-ng. Is this still an issue?

**Comment by dlabrecq** [comment]
Fabric-ui now uses the filter-fields component from patternfly-ng. This component no longer exists in ngx-widgets. Therefore, I've applied the fix in that repo, instead.

See https://github.com/patternfly/patternfly-ng/pull/89
